"""empty message

Revision ID: 42db0212c5db
Revises: cb39d83c6008
Create Date: 2021-02-17 17:17:04.909350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42db0212c5db'
down_revision = 'cb39d83c6008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo')
    # ### end Alembic commands ###
