"""empty message

Revision ID: ab344f479d6f
Revises: 42db0212c5db
Create Date: 2021-02-17 17:19:14.666862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab344f479d6f'
down_revision = '42db0212c5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo', 'age')
    # ### end Alembic commands ###
